"""create notifications table

Revision ID: bb4c4063bc91
Revises: 
Create Date: 2024-07-06 16:32:54.717044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4c4063bc91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('communication_type', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WHATSAPP', name='communicationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'CANCELED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
